### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by maxbrito** [sdhash/sdhash#2]
Hello,

I'm trying to compile the code (Linux) but get the following error message:

`sdhash-src/../sdbf/sdbf_defines.h:9:25: fatal error: openssl/bio.h: No such file or directory
compilation terminated.
make: *** [sdhash-src/sdhash.o] Error 1`

It seems the bio.h is missing. Any idea of how to solve this issue?

Thanks!

**Comment by hexavore** [comment]
You need to install the libssl-dev package. --VR

**Comment by maxbrito** [comment]
Ok, thank you very much.

I've installed it using:
`sudo apt-get install libssl-dev`

Perhaps worth adding this tidybit on the docs? It wasn't so clear what needed to be done for getting libssl working. Thanks.

**Comment by maxbrito** [comment]
Sorry, now I have the error:

```
sdhash-src/../sdbf/blooms.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
```

I guess this means the need to install protobuf. Looking around the web I found the following to work:

```
apt-get install protobuf-compiler libprotobuf-dev
```

but then got an out-of-date message:

```
sdhash-src/../sdbf/blooms.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
sdhash-src/../sdbf/blooms.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
sdhash-src/../sdbf/blooms.pb.h:14:2: error: #error your headers.
make: *** [sdhash-src/sdhash.o] Error 1
```

I'll try to get this error solved. Perhaps possible to request some compiled binaries for either Windows or Linux (x64)?

I just wanted to test-drive the binaries.

Thanks.

**Comment by hexavore** [comment]
Which version are you trying to compile? --VR

**Comment by hexavore** [comment]
On 12/1/2014 12:27 PM, Nuno Brito wrote:

> I just wanted to test-drive the binaries.

There is a binary for Windows:

https://github.com/google/protobuf/releases

Use the 3.4 version

--VR

**Comment by maxbrito** [comment]
Hello, my apologies as I wasn't clear. 

What I meant is asking if it is possible to make available the compiled binaries for sdhash (I'm using Linux x64 by default). Either a Windows or Linux executable of sdhash would be a good help to make testing easier for those without practical C compiling experience.

**Comment by candicenonsense** [comment]
Hiya,

We have windows binaries for sdhash, they are in the "Releases" section on
the sdhash github.   Older linux deb/rpm binaries are available on
sdhash.org as well.

Please try release 3.4's windows binaries here:

https://github.com/sdhash/sdhash/releases/tag/v3.4

Candice

**Comment by maxbrito** [comment]
Thank you. Maybe I'm finally reaching an older age where these things are getting more difficult for me to find.

I will test and provide feedback if needed. Thank you for the attention. From my side this bug is addressed, don't know if desired to include a link to the binaries in the README in case other folks stumble on the same question.

Wishing a good weekend,
Nuno.

**Comment by glaslos** [comment]
Is there any instructions available to recreate the `blooms.pb.h` with a more recent version of protobuf?

**Comment by glaslos** [comment]
Apparently with protobuf 2.6.1 all you need to do is `protoc -I ./ --cpp_out=sdbf/ blooms.proto`
